services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123456"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
